server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: 814362
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
